name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Deploy to Production
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}